# -*- coding: utf-8 -*-
"""mmq_coeficiente_linear_mássico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13mwEB5H8_soVwjaiQrZotxoZqBRyVE3R
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

def mmq (y, yerr):
    # Dados da tabela (positivos e negativos)
    x = np.array([0.5, 1, 1.5, 2])         # x

    # Modelo linear
    def linear(x, a, b):
        return a*x + b

    # Ajuste ponderado pelas incertezas
    popt, pcov = curve_fit(linear, x, y, sigma=yerr, absolute_sigma=True)
    a, b = popt
    da, db = np.sqrt(np.diag(pcov))

    print(f"Coeficiente Angular = {a:.2e} ± {da:.2e}")
    print(f"Interseção = {b:.2e} ± {db:.2e}")

    y_fit = linear(x, a, b)
    ss_res = np.sum((y - y_fit)**2)              # soma dos quadrados dos resíduos
    ss_tot = np.sum((y - np.mean(y))**2)         # soma total
    r2 = 1 - ss_res/ss_tot
    print(f"R² = {r2:.4f}")

    # Plot
    plt.errorbar(x, y, yerr=yerr, fmt='o', label='Dados')
    xx = np.linspace(min(x), max(x), 100)
    plt.plot(xx, linear(xx, *popt), 'r-', label=f"Ajuste: y = {a:.2e}x + {b:.2e}")
    plt.xlabel("x")
    plt.ylabel("ln(Io/I)")
    plt.legend(loc='upper left')
    plt.grid(True)
    plt.show()

    mi = a
    print(f'µ = {mi} ')
    mi_mass = mi/2.698900
    print(f'µ_mássico = {mi_mass} [cm²/g]')

#Alumínio - Isotrópico
y = np.array([0.0829220112, 0.1889545247, 0.2935982587, 0.3978149793])                    # ln(Io/I)
yerr = np.array([0.01520690633, 0.01564640534, 0.01609627286, 0.01655566368])              # incertezas ln(Io/I)
mmq(y, yerr)

#Alumínio - Colimado
y = np.array([0.09817278145, 0.1982555566, 0.2981018531, 0.3981222105])                    # ln(Io/I)
yerr = np.array([0.001769180601, 0.001843908891, 0.001920937271, 0.002])              # incertezas ln(Io/I)
mmq(y, yerr)

"""0,07440676933287275
0,07379907268868194
"""